[tool.poetry]
name = "transcribe"
version = "0.1.0"
description = ""
authors = ["Michael Bastos <bastosmichael@gmail.com>"]
readme = "README.md"
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.121.0"
uvicorn = "^0.38.0"
boto3 = "^1.21.0"
pydantic = "^1.9.0"
python-multipart = "^0.0.20"
requests = "^2.26.0"
python-dotenv = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^25.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
httpx = "^0.28.0"
pytest-asyncio = "^1.0.0"

[tool.poetry.scripts]
transcribe = "transcribe.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
